services:
  - type: web
    name: splitjourney
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: flet run main.py --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
